version: "3.9"

services:
  api:
    container_name: "project-api"
    build: .
    privileged: true
    ports:
      - 3000:3000
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./resources:/api/resources
      - ./file:/api/file